[general]
working_directory = "C:\\Users\\jbarthel"
import = ["./tokyo-night-default.toml"]

[font]

normal = { family = "FiraCode Nerd Font Mono" } 

bold =  { family = "FiraCode Nerd Font Mono",  style="bold" } 

italic =  { family = "FiraCode Nerd Font Mono", style="italic" } 

size = 14

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
dimensions = { columns = 150, lines = 35}
opacity = 0.99  

[cursor]
style = { shape = "Beam", blinking = "Off" }

[colors]
transparent_background_colors = true

# -----------------------------------------------------------------------------
# TokyoNight Alacritty Colors
# Theme: Tokyo Night
# Upstream: https://github.com/folke/tokyonight.nvim/raw/main/extras/alacritty/tokyonight_night.toml
# -----------------------------------------------------------------------------
# yellow = "#f9e2af"

# Default colors
[colors.primary]
background = '#1a1b26'
foreground = '#c0caf5'

# Normal colors
[colors.normal]
black = '#15161e'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#ff899d'
green = '#9fe044'
yellow = '#faba4a'
blue = '#8db0ff'
magenta = '#c7a9ff'
cyan = '#a4daff'
white = '#c0caf5'
[selection]
save_to_clipboard = true

[terminal] 
shell = "pwsh.exe" 

[mouse]
bindings = [
{ mouse = "Right", mods = "Control", action = "Paste" },
]

[keyboard]
bindings = [
{ key = "Backspace", mods = "Control",  chars = "\u0017"},
{ key = "PageUp", action = "ScrollHalfPageUp"},
{ key = "PageDown", action = "ScrollHalfPageDown"},
{ key = "N", mods = "Control | Shift", action = "SpawnNewInstance" }

]
