[general]

[font]

normal = { family = "FiraCode Nerd Font" } 

bold =  { family = "FiraCode Nerd Font",  style="bold" } 

italic =  { family = "FiraCode Nerd Font", style="italic" } 

size = 14

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
dimensions = { columns = 195, lines = 35}

[colors.bright]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#7aa2f7"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#ff9e64"
white = "#9699a8"
yellow = "#89ddff"

[colors.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#ff9e64"
white = "#b4b9f8"
yellow = "#f9e2af"

[colors.dim]
black = "#1a1b26"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#ff9e64"
white = "#9699a8"
yellow = "#f9e2af"

[colors.hints]

[colors.primary]
background = "#1a1b26"
foreground = "#c0caf5"

[selection]
save_to_clipboard = true

[mouse]
bindings = [
{ mouse = "Right", mods = "Control", action = "Paste" },
]
